name: vitscale
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch>=2.0.0
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8
  - cudatoolkit
  - pip
  - numpy
  - matplotlib
  - seaborn
  - pandas
  - scipy
  - scikit-learn
  - jupyter
  - ipykernel
  - tqdm
  - pyyaml
  - pip:
    - transformers>=4.30.0
    - datasets>=2.10.0
    - accelerate>=0.20.0
    - peft>=0.4.0
    - timm>=0.9.0
    - fvcore>=0.1.5
    - wandb>=0.15.0
    - tensorboard>=2.10.0
    - psutil>=5.9.0
